import { NavigationDrawer } from "@material";
import { NavPage } from "../types.slint";

export component NavDrawer {
    in property <NavPage> current-page: NavPage.GameList;
    callback navigate(NavPage);

    width: 280px;

    navigation-drawer := NavigationDrawer {
        width: parent.width;
        height: parent.height;

        groups: [
            {
                title: "",
                items: [
                    { icon: @image-url("../icons/GamesList.svg"), text: "Game List" },
                    { icon: @image-url("../icons/Package.svg"), text: "OptiScaler Versions" },
                    { icon: @image-url("../icons/Community.svg"), text: "Community" }
                ]
            },
            {
                title: "",
                items: [
                    { icon: @image-url("../icons/Settings.svg"), text: "Settings" },
                    { icon: @image-url("../icons/About.svg"), text: "About" }
                ]
            }
        ];

        selected(group, item) => {
            if group == 0 {
                if item == 0 {
                    root.navigate(NavPage.GameList);
                }
                if item == 1 {
                    root.navigate(NavPage.Versions);
                }
                if item == 2 {
                    root.navigate(NavPage.Community);
                }
            }
            if group == 1 {
                if item == 0 {
                    root.navigate(NavPage.Settings);
                }
                if item == 1 {
                    root.navigate(NavPage.About);
                }
            }
        }
    }
}
