# PKGBUILD for OptiTux
# Packages the locally-built .deb (produced by Tauri) for Arch Linux

pkgname=optitux-bin
_pkgname=OptiTux
pkgver=0.1.1
pkgrel=1
pkgdesc="A powerful GUI for managing OptiScaler and game library on Linux."
arch=('x86_64')
url="https://github.com/Spexxl/OptiTux-GUI"
license=('MIT')
depends=('webkit2gtk-4.1' 'libappindicator-gtk3' 'librsvg')
provides=('optitux')
conflicts=('optitux')
options=('!strip')

# Release source
# When building in CI, we point to the local file generated by Tauri
source=("${_pkgname}_${pkgver}_amd64.deb")
sha256sums=('SKIP')

package() {
    cd "${srcdir}"

    # Extract the .deb archive (ar format)
    ar x "${_pkgname}_${pkgver}_amd64.deb"

    # Extract the inner data tarball (extension varies: .xz, .zst, .gz)
    bsdtar -xf data.tar.* -C "${pkgdir}"

    # Ensure proper permissions for the binary
    if [ -f "${pkgdir}/usr/bin/optitux" ]; then
        chmod +x "${pkgdir}/usr/bin/optitux"
    fi
}
