# PKGBUILD for OptiTux
# Downloads the binary from the GitHub release and packages it for Arch Linux

pkgname=optitux-bin
_pkgname=OptiTux
pkgver=0.1.0
pkgrel=1
pkgdesc="A powerful GUI for managing OptiScaler and game library on Linux."
arch=('x86_64')
url="https://github.com/Spexxl/OptiTux-GUI"
license=('MIT')
depends=('webkit2gtk-4.1' 'libappindicator-gtk3' 'librsvg')
provides=('optitux')
conflicts=('optitux')
options=('!strip')

# Release source
# When building in CI, we point to the local file generated by Tauri
source=("local_deb::file://$(pwd)/../src-tauri/target/release/bundle/deb/${_pkgname}_${pkgver}_amd64.deb")
sha256sums=('SKIP')

package() {
    # Extract the data.tar.xz from the local debian package
    ar x local_deb
    tar -xJf data.tar.xz -C "${pkgdir}"
    
    # Ensure proper permissions for the binary
    if [ -f "${pkgdir}/usr/bin/optitux" ]; then
        chmod +x "${pkgdir}/usr/bin/optitux"
    fi
}
