# This is an example PKGBUILD for OptiTux.
# To publish this on AUR, you would create a repository named 'optitux-bin' 
# and upload this file there.

pkgname=optitux-bin
_pkgname=OptiTux
pkgver=0.1.0
pkgrel=1
pkgdesc="A powerful GUI for managing OptiScaler and game library on Linux."
arch=('x86_64')
url="https://github.com/Spexxl/OptiTux-GUI"
license=('MIT')
depends=('webkit2gtk-4.1' 'libappindicator-gtk3' 'librsvg')
provides=('optitux')
conflicts=('optitux')
options=('!strip' '!empty')

# Here we point to the .deb generated by your GitHub Actions
source=("${url}/releases/download/v${pkgver}/${_pkgname}_${pkgver}_amd64.deb")

# You can update this hash when you release a new version, or use 'SKIP' for testing
sha256sums=('SKIP')

package() {
    # Extract the data.tar.xz from the debian package
    tar -xJf data.tar.xz -C "${pkgdir}"
    
    # Ensure the executable has the right permissions
    chmod +x "${pkgdir}/usr/bin/optitux"
}
