import { NavPage } from "types.slint";
import { NavDrawer } from "components/nav_drawer.slint";
import { GameListPage } from "pages/game_list_page.slint";
import { VersionsPage } from "pages/versions_page.slint";
import { CommunityPage } from "pages/community_page.slint";
import { SettingsPage } from "pages/settings_page.slint";
import { AboutPage } from "pages/about_page.slint";

export component MainWindow inherits Window {
    title: "OptiTux";
    preferred-width: 1100px;
    preferred-height: 720px;
    background: #0f1117;

    property <NavPage> current-page: NavPage.GameList;

    HorizontalLayout {
        spacing: 0px;

        NavDrawer {
            current-page: root.current-page;
            navigate(page) => { root.current-page = page; }
        }

        Rectangle {
            width: 1px;
            background: #252932;
        }

        Rectangle {
            background: #0f1117;
            clip: true;

            if root.current-page == NavPage.GameList: GameListPage {}
            if root.current-page == NavPage.Versions: VersionsPage {}
            if root.current-page == NavPage.Community: CommunityPage {}
            if root.current-page == NavPage.Settings: SettingsPage {}
            if root.current-page == NavPage.About: AboutPage {}
        }
    }
}
