name: Release

on:
  push:
    tags:
      - 'v*'
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf flatpak flatpak-builder libarchive-tools

      - name: Install frontend dependencies
        run: npm install

      - name: Build the app (DEB and RPM)
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WEBKIT_DISABLE_COMPOSITING_MODE: 1
          WEBKIT_DISABLE_DMABUF_RENDERER: 1
        with:
          tagName: ${{ github.ref_name }}
          releaseName: 'OptiTux v__VERSION__'
          releaseBody: |
            ## OptiTux v__VERSION__

            | Plataforma | Arquivo |
            |---|---|
            | Linux Flatpak | `.flatpak` |
            | Linux Arch/CachyOS | `.pkg.tar.zst` |
            | Linux Debian/Ubuntu | `.deb` |
            | Linux Fedora/RHEL | `.rpm` |
          releaseDraft: true
          prerelease: false

      - name: Build Arch Package (.pkg.tar.zst)
        run: |
          mkdir -p arch_build
          cp PKGBUILD arch_build/
          docker run --rm -v $(pwd):/workspace -w /workspace/arch_build archlinux:latest bash -c "
            pacman -Sy --noconfirm --noprogressbar base-devel binutils sudo
            useradd -m builduser && chown -R builduser:builduser /workspace/arch_build
            sudo -u builduser makepkg --noconfirm --nodeps
            chown -R $(id -u):$(id -g) .
          "
          mv arch_build/*.pkg.tar.zst ./OptiTux-x86_64.pkg.tar.zst

      - name: Build Flatpak
        run: |
          mkdir -p flatpak_app
          ar x src-tauri/target/release/bundle/deb/OptiTux_*_amd64.deb
          bsdtar -xf data.tar.* -C flatpak_app/
          cp src-tauri/target/release/optitux flatpak_app/
          flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          flatpak-builder --repo=repo --force-clean build-dir com.sll.optitux-gui.json
          flatpak build-bundle repo OptiTux.flatpak com.sll.optitux-gui

      - name: Upload Extra Formats to Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            OptiTux.flatpak
            OptiTux-x86_64.pkg.tar.zst
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
